str=input("enter any string")
print(len(str))
print("lower case",str.lower())
print("upper case",str.upper())
print(str.split('a'))
print(str.startswith('a'))
print(str.endswith('a'))
print(str[::-1])
print(str.replace('a','@'))